# Generated by Django 4.1.5 on 2023-02-14 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PulseSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=205)),
                ('activity_type', models.CharField(choices=[('WT', 'Work task'), ('TB', 'Take a break'), ('DFV', 'Day off/vacation')], max_length=20)),
                ('num_hours', models.CharField(max_length=10)),
                ('emotional_rate_status', models.CharField(choices=[('happy', '😀'), ('tired', '😫'), ('illness', '🤒'), ('taking_break_or_vacation', '😎'), ('sleeping', '😴'), ('need_help', '😕'), ('upset', '😢'), ('normal', '😐')], max_length=35)),
                ('activity_description', models.TextField(blank=True, null=True)),
                ('work_stressor_status', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=5)),
                ('activity_created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
