# Generated by Django 4.1.5 on 2023-02-15 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_employee'),
        ('workrecords', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pulsesurvey',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pulse_survey', to='users.employee'),
        ),
    ]
