# Generated by Django 4.1.5 on 2023-03-22 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_employer'),
        ('workrecords', '0002_alter_pulsesurvey_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.PositiveIntegerField()),
                ('dietary_restrictions', models.CharField(max_length=100)),
                ('goal', models.CharField(blank=True, max_length=100)),
                ('allergy', models.CharField(max_length=100)),
                ('budget', models.FloatField()),
                ('cusine', models.CharField(max_length=100)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.employee')),
            ],
        ),
    ]
