# Generated by Django 4.1.5 on 2023-03-22 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workrecords', '0003_mealplan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mealplan',
            old_name='cusine',
            new_name='cuisine',
        ),
    ]
