# Generated by Django 4.1.5 on 2023-04-19 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workrecords', '0005_fooditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='food_item_type',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('recipe', 'Recipe')], max_length=30),
        ),
    ]
