# Generated by Django 4.1.5 on 2023-04-20 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workrecords', '0006_alter_fooditem_food_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
