# Generated by Django 4.1.5 on 2023-04-26 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_employer'),
        ('workrecords', '0008_alter_fooditem_allergy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employee')),
                ('food_items', models.ManyToManyField(related_name='orders', to='workrecords.fooditem')),
            ],
        ),
    ]
