# Generated by Django 4.1.5 on 2023-05-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workrecords', '0010_alter_fooditem_allergy'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='food_meal_image',
            field=models.ImageField(blank=True, null=True, upload_to='meal_item_images/'),
        ),
    ]
